"""initial schema

Revision ID: 079d90221a81
Revises:
Create Date: 2026-08-25 11:31:40.216857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079d90221a81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_firms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('law_firm_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'lawyer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['law_firm_id'], ['law_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_law_firm_id'), 'users', ['law_firm_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('law_firm_id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('case_name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('opposing_party', sa.String(length=255), nullable=True),
    sa.Column('case_type', sa.Enum('is_hukuku', 'ticaret_hukuku', 'sozlesme', 'kira', 'icra', 'diger', name='casetype'), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=True),
    sa.Column('assigned_lawyer_id', sa.String(length=36), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=False),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('devam_eden', 'durusma_bekleyen', 'karar_bekleyen', 'kapali', name='casestatus'), nullable=False),
    sa.Column('outcome', sa.Enum('ongoing', 'won', 'lost', 'settled', name='caseoutcome'), nullable=False),
    sa.Column('case_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_lawyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['law_firm_id'], ['law_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_law_firm_id'), 'cases', ['law_firm_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('law_firm_id', sa.String(length=36), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('filing', 'hearing', 'submission', 'expert_report', 'legal_update', 'note', 'other', name='caseeventtype'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['law_firm_id'], ['law_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_events_law_firm_id'), 'case_events', ['law_firm_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('law_firm_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'docx', 'txt', name='documenttype'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['law_firm_id'], ['law_firms.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_law_firm_id'), 'documents', ['law_firm_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('law_firm_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='simulationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('context_version', sa.String(length=20), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('failure_category', sa.String(length=30), nullable=True),
    sa.Column('current_stage', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['law_firm_id'], ['law_firms.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_case_id'), 'simulations', ['case_id'], unique=False)
    op.create_index(op.f('ix_simulations_law_firm_id'), 'simulations', ['law_firm_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('law_firm_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='taskstatus'), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['law_firm_id'], ['law_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_case_id'), 'tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_tasks_law_firm_id'), 'tasks', ['law_firm_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=True),
    sa.Column('law_firm_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.Enum('case_summary', 'simulation_report', 'handover_summary', name='analysistype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strong_points', sa.JSON(), nullable=False),
    sa.Column('weak_points', sa.JSON(), nullable=False),
    sa.Column('opposing_arguments', sa.JSON(), nullable=False),
    sa.Column('missing_information', sa.JSON(), nullable=False),
    sa.Column('possible_scenarios', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('assessment_score', sa.Integer(), nullable=False),
    sa.Column('assessment_confidence', sa.Enum('low', 'medium', 'high', name='assessmentconfidence'), nullable=False),
    sa.Column('ai_disclaimer', sa.Text(), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['law_firm_id'], ['law_firms.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_index(op.f('ix_ai_analyses_case_id'), 'ai_analyses', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_law_firm_id'), 'ai_analyses', ['law_firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyses_law_firm_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_case_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_tasks_law_firm_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_case_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_simulations_law_firm_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_case_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_documents_law_firm_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_case_events_law_firm_id'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_cases_law_firm_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_law_firm_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('law_firms')
    # ### end Alembic commands ###
