"""add unique constraint on case_number per firm

Revision ID: 9b5e49bd0875
Revises: 079d90221a81
Create Date: 2026-08-25 12:00:08.084261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5e49bd0875'
down_revision: Union[str, Sequence[str], None] = '079d90221a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    SQLite has no ALTER TABLE ADD CONSTRAINT - batch mode is required
    (it copies the table under a new schema and swaps it in). Postgres
    would accept the plain op.create_unique_constraint(...) call, but
    batch_alter_table works correctly on both dialects, so it's used
    unconditionally here rather than branching on dialect.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cases_law_firm_id_case_number', ['law_firm_id', 'case_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cases_law_firm_id_case_number', type_='unique')
    # ### end Alembic commands ###
