"use client";

import { useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { AlertTriangle, ArrowLeft, ArrowRight, BadgeCheck, Bookmark, BriefcaseBusiness, CalendarDays, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, Eye, FileCheck2, FileText, Filter, Globe2, Languages, LockKeyhole, MapPin, MessageSquare, MoreHorizontal, Search, Send, ShieldCheck, SlidersHorizontal, Sparkles, Star, UserCheck, Users, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, Disclaimer, EmptyState, PageTitle, Progress } from "@/components/ui";
import { cases, lawyers } from "@/lib/mock-data";

export function LawyerDashboard(){
  const chart=[{m:"Feb",v:22},{m:"Mar",v:31},{m:"Apr",v:26},{m:"May",v:42},{m:"Jun",v:39},{m:"Jul",v:56}];
  return <AppShell role="lawyer" active="Overview"><PageTitle eyebrow="Professional workspace" title="Good morning, Aylin" text="You have 12 new case matches across your selected jurisdictions." action={<Button href="/lawyer/marketplace">Browse matching cases <ArrowRight/></Button>}/>
    <div className="lawyer-status-banner"><div><span className="lawyer-avatar-lg">AD<BadgeCheck/></span><div><strong>Your profile is verified and visible</strong><p>Turkey · European Union · Employment · Cross-border disputes</p></div></div><div><span>Professional plan</span><Progress value={68}/><small>17 of 25 case views used</small></div><Button href="/lawyer/profile" variant="secondary">View profile</Button></div>
    <div className="metric-grid five"><LawMetric label="Case matches" value="56" change="+18% this month" icon={<BriefcaseBusiness/>}/><LawMetric label="Offers submitted" value="12" change="4 awaiting response" icon={<Send/>}/><LawMetric label="Acceptance rate" value="33%" change="+5% vs last month" icon={<CheckCircle2/>}/><LawMetric label="Profile views" value="148" change="+24 this week" icon={<Eye/>}/><LawMetric label="Active conversations" value="7" change="2 unread" icon={<MessageSquare/>}/></div>
    <div className="content-grid"><section className="panel panel-wide"><PanelHead title="Best matching cases" action={<a href="/lawyer/marketplace">View marketplace</a>}/><div className="matching-list">{cases.map((c,i)=><a href={`/lawyer/cases/${c.id}`} key={c.id} className="matching-row"><span className="match-score">{96-i*5}<small>% match</small></span><div><div><Badge tone={c.crossBorder?"teal":"blue"}>{c.crossBorder?"Cross-border":"Local"}</Badge><Badge tone={c.urgency==="High"?"red":"amber"}>{c.urgency} urgency</Badge></div><h3>{c.title}</h3><p>{c.summary}</p><span><Globe2/>{c.jurisdictions.join(" + ")}</span><span><Languages/>{c.languages.join(", ")}</span></div><div><strong>{c.budget}</strong><small>Published {i===0?"24 min":"1 day"} ago</small><ArrowRight/></div></a>)}</div></section>
      <aside className="panel analytics-panel"><PanelHead title="Profile discovery" action={<select><option>6 months</option></select>}/><div className="chart-total"><strong>148</strong><span>profile views this month</span></div><div className="mini-chart"><ResponsiveContainer width="100%" height={180}><AreaChart data={chart}><defs><linearGradient id="tealFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0d8a78" stopOpacity={.28}/><stop offset="100%" stopColor="#0d8a78" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e9e8"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"#7a8583"}}/><Tooltip/><Area type="monotone" dataKey="v" stroke="#0d8a78" strokeWidth={2} fill="url(#tealFill)"/></AreaChart></ResponsiveContainer></div><div className="analytics-note"><Sparkles/><span><b>Profile insight</b>Cross-border employment cases drive 41% of your profile views.</span></div></aside></div>
    <div className="content-grid lower"><section className="panel panel-wide" id="offers"><PanelHead title="Recent offers" action={<a href="#">View all</a>}/><div className="offer-table"><div className="table-head"><span>Case</span><span>Proposed model</span><span>Submitted</span><span>Status</span><span/></div>{[["Software contractor termination","Initial consultation","Today","Viewed"],["Executive compensation dispute","Hourly representation","Yesterday","Pending"],["German subsidiary restructure","Fixed scope review","23 Jul","Accepted"]].map(r=><div className="table-row" key={r[0]}><span><b>{r[0]}</b><small>Employment · Cross-border</small></span><span>{r[1]}</span><span>{r[2]}</span><span><Badge tone={r[3]==="Accepted"?"green":r[3]==="Viewed"?"blue":"amber"}>{r[3]}</Badge></span><button><MoreHorizontal/></button></div>)}</div></section><aside className="panel jurisdiction-card"><PanelHead title="Jurisdiction coverage"/><div className="coverage-ring"><span>82%</span></div><h3>Strong market coverage</h3><p>You match cases in Turkey, the EU and selected Germany-connected disputes.</p><a href="/lawyer/profile">Update coverage <ArrowRight/></a></aside></div>
  </AppShell>;
}
function LawMetric({label,value,change,icon}:{label:string;value:string;change:string;icon:React.ReactNode}){return <div className="metric-card"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{change}</small></div>}
function PanelHead({title,action}:{title:string;action?:React.ReactNode}){return <div className="panel-head"><h2>{title}</h2>{action}</div>}

export function LawyerMarketplace(){
  const [search,setSearch]=useState(""); const [cross,setCross]=useState(true);
  const filtered=cases.filter(c=>(!cross||c.crossBorder)&&c.title.toLowerCase().includes(search.toLowerCase()));
  return <AppShell role="lawyer" active="Case marketplace"><PageTitle eyebrow="Qualified case leads" title="Case marketplace" text="Anonymized cases matched to your licenses, languages and selected practice areas."/>
    <div className="market-toolbar"><div className="market-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by issue, category or jurisdiction"/></div><button><SlidersHorizontal/> More filters <Badge>4</Badge></button><select><option>Best match</option><option>Newest</option><option>Most urgent</option></select></div>
    <div className="filter-chips"><button>Jurisdiction: Any <ChevronDown/></button><button>Employment <X/></button><button>English or Turkish <X/></button><button className={cross?"active":""} onClick={()=>setCross(!cross)}><Globe2/> Cross-border only</button><button>Budget: $500+ <X/></button><button className="clear">Clear all</button></div>
    <div className="market-layout"><aside className="filter-panel"><h3><Filter/> Filters</h3><FilterGroup title="Country"><label><input type="checkbox" defaultChecked/> Turkey <span>18</span></label><label><input type="checkbox" defaultChecked/> Germany <span>9</span></label><label><input type="checkbox"/> United Kingdom <span>7</span></label><label><input type="checkbox"/> United States <span>6</span></label></FilterGroup><FilterGroup title="Case stage"><label><input type="checkbox" defaultChecked/> Report ready <span>24</span></label><label><input type="checkbox"/> Gathering evidence <span>11</span></label></FilterGroup><FilterGroup title="Evidence completeness"><label><input type="checkbox"/> High <span>16</span></label><label><input type="checkbox"/> Medium <span>21</span></label></FilterGroup><FilterGroup title="Consultation"><label><input type="checkbox"/> Remote accepted <span>38</span></label><label><input type="checkbox"/> In-person <span>12</span></label></FilterGroup></aside>
      <section className="market-results"><div className="results-head"><span><strong>{filtered.length}</strong> highly relevant cases</span><small>Private information hidden until approval</small></div>{filtered.length?filtered.map((c,i)=><MarketCase key={c.id} c={c} score={96-i*6}/>):<EmptyState title="No cases match these filters" text="Clear a filter to see more qualified cases." action={<Button variant="secondary" onClick={()=>setCross(false)}>Clear cross-border filter</Button>}/>}</section>
    </div></AppShell>;
}
function FilterGroup({title,children}:{title:string;children:React.ReactNode}){return <div className="filter-group"><button>{title}<ChevronDown/></button><div>{children}</div></div>}
function MarketCase({c,score}:{c:(typeof cases)[number];score:number}){return <article className="market-card"><div className="market-card-top"><div><Badge tone={c.crossBorder?"teal":"blue"}>{c.crossBorder?<><Globe2/> Cross-border</>:<>Local case</>}</Badge><Badge tone={c.urgency==="High"?"red":"amber"}>{c.urgency} urgency</Badge><Badge tone="green"><UserCheck/> User verified</Badge></div><button><Bookmark/></button></div><a href={`/lawyer/cases/${c.id}`}><h2>{c.title}</h2></a><p>{c.summary}</p><div className="market-facts"><span><MapPin/>{c.jurisdictions.join(" + ")}</span><span><BriefcaseBusiness/>{c.category}</span><span><Languages/>{c.languages.join(", ")}</span><span><CircleDollarSign/>{c.budget}</span></div><div className="evidence-complete"><div><span>Evidence completeness</span><strong>{c.completion}%</strong></div><Progress value={c.completion}/><small><FileCheck2/> {c.evidence.length} document summaries · AI-organized report available</small></div><div className="market-card-foot"><div><span className="match-circle">{score}%</span><div><strong>Excellent match</strong><small>Jurisdiction, language & specialization</small></div></div><div><small>Published {c.id==="CB-1048"?"24 minutes":"1 day"} ago</small><Button href={`/lawyer/cases/${c.id}`} variant="secondary">Review case <ArrowRight/></Button></div></div></article>}

export function LawyerCaseDetail({id}:{id:string}){
  const c=cases.find(x=>x.id===id)||cases[0]; const [offer,setOffer]=useState(false); const [sent,setSent]=useState(false);
  return <AppShell role="lawyer" active="Case marketplace"><div className="case-detail-head"><div><a href="/lawyer/marketplace"><ArrowLeft/> Marketplace</a><div><Badge tone={c.crossBorder?"teal":"blue"}>{c.crossBorder?"Cross-border":"Local case"}</Badge><Badge tone={c.urgency==="High"?"red":"amber"}>{c.urgency} urgency</Badge><Badge tone="green"><UserCheck/> User verified</Badge></div><h1>{c.title}</h1><p>Anonymous case · {c.id} · Published 24 minutes ago</p></div><div><Button variant="secondary"><Bookmark/> Save</Button><Button onClick={()=>setOffer(true)}>Express interest <ArrowRight/></Button></div></div><div className="privacy-ribbon"><LockKeyhole/><div><strong>Private user information is protected</strong><p>You can see the anonymized report and document categories. Identity and original documents require user approval.</p></div><Badge tone="green">Access controlled</Badge></div>
    <div className="detail-layout"><article><section className="panel detail-section"><PanelHead title="Anonymous case summary"/><p className="detail-lede">{c.summary} Based on the information provided, the user is seeking a preliminary review of possible claims, any urgent deadlines and practical next steps.</p><div className="detail-facts"><span><small>Jurisdictions</small><strong>{c.jurisdictions.join(" + ")}</strong></span><span><small>Category</small><strong>{c.category}</strong></span><span><small>Languages</small><strong>{c.languages.join(", ")}</strong></span><span><small>Budget range</small><strong>{c.budget}</strong></span></div></section>
      <section className="panel detail-section"><PanelHead title="Case timeline"/><div className="timeline">{[["02 Jan 2024","Employment agreement signed"],["Mar–May 2026","Salary payments delayed"],["18 Jun 2026","Termination email received"],["26 Jul 2026","Case published anonymously"]].map((x,i)=><div key={x[0]}><span className={i===3?"current":""}/><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div></section>
      <section className="panel detail-section"><PanelHead title="Possible legal issues" action={<Badge tone="amber">Requires lawyer review</Badge>}/><div className="detail-issues">{["Unpaid salary claim","Notice period dispute","Contract violation","Termination process"].map((x,i)=><div key={x}><span>{i+1}</span><div><strong>{x}</strong><p>{i<2?"Supporting documents are available in summarized form.":"The AI report flags this as a possible related issue."}</p></div><Badge tone={i<2?"blue":"neutral"}>{i<2?"Priority":"Potential"}</Badge></div>)}</div></section>
      <section className="panel detail-section"><PanelHead title="Evidence overview" action={<Badge tone="green">{c.completion}% complete</Badge>}/><div className="evidence-categories">{c.evidence.map((x,i)=><div key={x}><FileText/><div><strong>{x}</strong><span>{i<2?"Strong relevance":"Moderate relevance"} · Original locked</span></div><LockKeyhole/></div>)}</div><div className="locked-docs"><ShieldCheck/><div><strong>Original files are not visible</strong><p>Request access in your offer. The user decides which documents to share.</p></div></div></section>
      <Disclaimer/></article>
      <aside><section className="panel user-expectations"><h3>User expectations</h3><dl><dt>Preferred outcome</dt><dd>Recover unpaid salary and understand options</dd><dt>Consultation</dt><dd>Remote or in-person</dd><dt>Response preference</dt><dd>Written introduction first</dd><dt>Availability</dt><dd>Weekdays after 17:00</dd></dl></section><section className="panel match-explanation"><div className="big-match">96<small>% match</small></div><h3>Why this case matches you</h3><p><Check/> Licensed in Turkey</p><p><Check/> Employment specialization</p><p><Check/> Turkish & English</p><p><Check/> Cross-border experience</p><Button onClick={()=>setOffer(true)} className="full">Submit representation offer</Button><Button variant="ghost" className="full"><MessageSquare/> Request more information</Button></section></aside></div>
    {offer&&<OfferModal close={()=>setOffer(false)} sent={sent} onSend={()=>setSent(true)}/>}</AppShell>;
}

function OfferModal({close,sent,onSend}:{close:()=>void;sent:boolean;onSend:()=>void}){
  if(sent)return <div className="modal-backdrop"><div className="offer-modal success-offer"><button className="modal-close" onClick={close}><X/></button><div className="success-icon"><Check/></div><Badge tone="green">Offer submitted</Badge><h2>Your introduction has been sent.</h2><p>The user will review your profile and proposal. Personal information remains hidden until they approve contact.</p><Button onClick={close} className="full">Return to case</Button></div></div>;
  return <div className="modal-backdrop"><div className="offer-modal" role="dialog" aria-modal="true" aria-labelledby="offer-title"><header><div><span className="eyebrow">Representation proposal</span><h2 id="offer-title">Express interest in this case</h2><p>Your verified profile will be shared with the user.</p></div><button onClick={close}><X/></button></header><div className="offer-body"><label>Introduction<textarea rows={4} defaultValue="Hello, I am a Turkish employment lawyer with 12 years of experience advising employees and employers on termination and wage disputes."/></label><label>Relevant experience<textarea rows={3} defaultValue="I have handled more than 40 employment termination matters, including cases with cross-border elements and multilingual evidence."/></label><label>Proposed next steps<textarea rows={3} defaultValue="I would first verify the employment dates, review the termination notice and confirm any applicable filing deadlines."/></label><div className="form-grid"><label>Consultation fee<select><option>$150 initial consultation</option><option>No-fee introductory call</option></select></label><label>Representation model<select><option>Hourly representation</option><option>Fixed scope review</option><option>Retainer</option></select></label><label>Initial timeline<select><option>Review within 2 business days</option></select></label><label>Availability<select><option>This week</option><option>Next week</option></select></label></div><label>Languages<div className="chip-select"><button className="selected"><Check/> Turkish</button><button className="selected"><Check/> English</button><button>German</button></div></label><label className="checkbox request-access"><input type="checkbox"/> Request access to the employment contract and termination letter after user approval</label><label className="checkbox consent"><input type="checkbox" defaultChecked/> I understand that access to personal data requires user approval.</label></div><footer><span><ShieldCheck/> Sent securely through CaseBridge</span><div><Button variant="secondary" onClick={close}>Cancel</Button><Button onClick={onSend}>Submit offer <Send/></Button></div></footer></div></div>;
}

export function LawyerProfile(){
  const lawyer=lawyers[0];
  return <AppShell role="lawyer" active="Profile"><div className="profile-hero"><div className="profile-avatar">{lawyer.initials}<span><BadgeCheck/></span></div><div><Badge tone="green"><UserCheck/> Identity and license verified</Badge><h1>{lawyer.name}</h1><p>Employment & cross-border disputes · Istanbul, Turkey</p><div className="profile-stats"><span><strong>12</strong> years experience</span><span><strong>&lt; 4h</strong> response time</span><span><strong>96%</strong> profile complete</span></div></div><div><Button variant="secondary">Edit profile</Button><Button>Preview public profile</Button></div></div><div className="profile-layout"><article><section className="panel profile-section"><h2>Professional biography</h2><p>I advise individuals and businesses on Turkish employment law, termination disputes and cross-border workplace matters. My practice focuses on clear early assessment, evidence preservation and practical resolution strategies.</p></section><section className="panel profile-section"><h2>Licenses & jurisdictions</h2><div className="license-row"><span className="flag">TR</span><div><strong>Turkey</strong><p>Istanbul Bar Association · License 34218</p></div><Badge tone="green"><UserCheck/>Verified</Badge></div><div className="license-row"><span className="flag">EU</span><div><strong>European Union matters</strong><p>Cross-border advisory profile</p></div><Badge tone="blue">Professional coverage</Badge></div></section><section className="panel profile-section"><h2>Areas of practice</h2><div className="practice-grid">{["Employment disputes","Termination & severance","Unpaid compensation","Commercial contracts","Cross-border employment","Workplace investigations"].map(x=><span key={x}><Check/> {x}</span>)}</div></section><section className="panel profile-section"><h2>Cross-border experience</h2><p>Regularly coordinates matters involving Turkey, Germany and the United Kingdom, including multilingual contracts, remote employment and foreign parent companies.</p><div className="country-route"><span>Turkey</span><ArrowRight/><span>Germany</span><ArrowRight/><span>United Kingdom</span></div></section></article><aside><section className="panel consultation-card"><h3>Consultation options</h3><p><Check/> Video consultation</p><p><Check/> Phone consultation</p><p><Check/> In-person in Istanbul</p><p><Check/> Written document review</p><hr/><span>Languages</span><div className="profile-tags"><Badge>Turkish · Native</Badge><Badge>English · Fluent</Badge><Badge>German · Professional</Badge></div><Button className="full"><CalendarDays/> Request consultation</Button></section><section className="panel reviews-card"><h3>Client reviews</h3><div><strong>4.9</strong><span>{[1,2,3,4,5].map(x=><Star key={x}/>)}</span><small>Reviews available after pilot launch</small></div></section></aside></div></AppShell>;
}
