"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, BriefcaseBusiness, CalendarDays, Check, CheckCircle2, ChevronDown, CircleHelp, Clock3, Download, Eye, File, FileCheck2, FileClock, FilePlus2, FileText, Globe2, Info, Languages, LockKeyhole, MessageSquare, Mic, MoreHorizontal, Paperclip, Plus, Save, Search, Send, ShieldCheck, Sparkles, Trash2, UploadCloud, UserCheck, Users, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, Disclaimer, EmptyState, PageTitle, Progress, StepPill } from "@/components/ui";
import { aiService, analysisStages } from "@/lib/ai-service";
import { cases, jurisdictions, legalCategories, lawyers } from "@/lib/mock-data";

export function IndividualDashboard() {
  return <AppShell active="Overview"><PageTitle eyebrow="Sunday, 26 July" title="Good morning, Elif" text="Your case workspace is private. Here is what needs your attention." action={<Button href="/new-case"><Plus/> Start a new case</Button>} />
    <div className="dashboard-notice"><Sparkles/><div><strong>Your employment case report is ready</strong><p>Review the preliminary assessment and 2 missing evidence suggestions.</p></div><Button href="/report" variant="secondary">View report <ArrowRight/></Button></div>
    <div className="metric-grid">
      <Metric label="Active cases" value="3" detail="1 needs attention" icon={<FileText/>}/><Metric label="Lawyer responses" value="8" detail="+3 since yesterday" icon={<Users/>}/><Metric label="Documents" value="12" detail="All securely stored" icon={<FileCheck2/>}/><Metric label="Profile privacy" value="Protected" detail="Anonymous by default" icon={<ShieldCheck/>}/>
    </div>
    <div className="content-grid"><section className="panel panel-wide"><PanelHead title="Your cases" action={<a href="#">View all</a>}/><div className="case-list">{cases.map(c=><CaseRow key={c.id} c={c}/>)}</div></section>
      <aside className="panel"><PanelHead title="Activity" action={<button><MoreHorizontal/></button>}/><div className="activity-list"><Activity icon={<Users/>} tone="teal" title="New lawyer response" text="A verified lawyer responded to your e-commerce case." time="24 min ago"/><Activity icon={<FileCheck2/>} tone="blue" title="Report generated" text="Your employment dispute report is ready." time="2 hours ago"/><Activity icon={<FilePlus2/>} tone="amber" title="Document requested" text="Add your signed salary statement if available." time="Yesterday"/></div></aside>
    </div>
    <div className="content-grid lower"><section className="panel panel-wide"><PanelHead title="Recent documents" action={<Button variant="ghost"><UploadCloud/> Upload</Button>}/><div className="document-table"><div className="table-head"><span>Document</span><span>Case</span><span>AI status</span><span>Added</span></div>{[["Employment contract.pdf","Unpaid salary dispute","Classified","Today"],["Termination email.pdf","Unpaid salary dispute","Relevant · 91%","Today"],["order-confirmation.pdf","E-commerce refund","Classified","Yesterday"]].map(r=><div className="table-row" key={r[0]}><span><FileText/> <b>{r[0]}</b></span><span>{r[1]}</span><span><Badge tone="green">{r[2]}</Badge></span><span>{r[3]}</span></div>)}</div></section>
      <aside className="panel privacy-mini"><PanelHead title="Privacy controls"/><LockKeyhole/><h3>You are in control</h3><p>No lawyer can see your identity or original documents without permission.</p><a href="/settings">Review permissions <ArrowRight/></a></aside></div>
  </AppShell>;
}

function Metric({label,value,detail,icon}:{label:string;value:string;detail:string;icon:React.ReactNode}){return <div className="metric-card"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function PanelHead({title,action}:{title:string;action?:React.ReactNode}){return <div className="panel-head"><h2>{title}</h2>{action}</div>}
function statusTone(status:string){return status==="Report ready"?"green":status==="Published"?"blue":status==="Lawyer responses received"?"teal":"amber"}
function CaseRow({c}:{c:(typeof cases)[number]}){return <a className="case-row" href={c.id==="CB-1048"?"/report":"/publish"}><div className="case-icon"><FileText/></div><div className="case-main"><span className="case-id">{c.id} · {c.category}</span><h3>{c.title}</h3><div className="case-meta"><span><Globe2/>{c.jurisdictions.join(" + ")}</span><span><Clock3/>{c.updated}</span></div></div><div className="case-progress"><Badge tone={statusTone(c.status)}>{c.status}</Badge><div><Progress value={c.completion}/><small>{c.completion}%</small></div></div><div className="response-count"><Users/><strong>{c.responses}</strong><small>responses</small></div><ArrowRight className="row-arrow"/></a>}
function Activity({icon,tone,title,text,time}:{icon:React.ReactNode;tone:string;title:string;text:string;time:string}){return <div className="activity"><div className={`activity-icon ${tone}`}>{icon}</div><div><strong>{title}</strong><p>{text}</p><small>{time}</small></div></div>}

const wizardLabels=["Scope","Jurisdiction","Category","Description","AI questions","Evidence","Review"];
type CaseDraft={scope:string;primary:string;secondary:string[];category:string;description:string;date:string;parties:string;outcome:string;deadline:string};
const emptyDraft:CaseDraft={scope:"cross-border",primary:"Turkey",secondary:["Germany"],category:"Employment",description:"My employer ended my employment after several delayed salary payments. I received a termination email but no formal notice.",date:"2026-06-18",parties:"My employer and me",outcome:"Recover unpaid salary and understand my options",deadline:"2026-08-15"};

export function NewCaseWizard(){
  const [step,setStep]=useState(1); const [draft,setDraft]=useState<CaseDraft>(emptyDraft); const [saved,setSaved]=useState(true); const [files,setFiles]=useState(["Employment contract.pdf","Termination email.pdf"]);
  useEffect(()=>{const savedDraft=localStorage.getItem("casebridge-draft");if(savedDraft)try{setDraft(JSON.parse(savedDraft))}catch{}},[]);
  useEffect(()=>{setSaved(false);const t=setTimeout(()=>{localStorage.setItem("casebridge-draft",JSON.stringify(draft));setSaved(true)},500);return()=>clearTimeout(t)},[draft]);
  const next=()=>{if(step===7)window.location.href="/analysis";else setStep(s=>Math.min(7,s+1))};
  return <AppShell active="New case"><div className="wizard-top"><div><a href="/dashboard"><ArrowLeft/> Dashboard</a><h1>Create a new case</h1></div><span className="autosave">{saved?<><Check/> Saved</>:<><Save/> Saving...</>}</span></div>
    <div className="wizard-layout"><aside className="wizard-steps">{wizardLabels.map((l,i)=><StepPill key={l} number={i+1} label={l} active={step===i+1} complete={step>i+1}/>) }<div className="draft-help"><CircleHelp/><strong>Need a break?</strong><p>Your progress is saved automatically.</p></div></aside>
      <section className="wizard-card"><div className="wizard-progress-mobile"><span>Step {step} of 7</span><Progress value={Math.round(step/7*100)}/></div>{renderWizardStep(step,draft,setDraft,files,setFiles)}
        <div className="wizard-nav"><Button variant="ghost" disabled={step===1} onClick={()=>setStep(s=>Math.max(1,s-1))}><ArrowLeft/> Back</Button><span>Step {step} of 7</span><Button onClick={next}>{step===7?"Analyze my case":"Continue"} <ArrowRight/></Button></div></section>
    </div></AppShell>;
}

function renderWizardStep(step:number,draft:CaseDraft,setDraft:(d:CaseDraft)=>void,files:string[],setFiles:(f:string[])=>void){
  if(step===1)return <WizardSection eyebrow="Case scope" title="How is this legal problem connected to countries?" text="Choose the closest fit. You can change this later."><div className="option-cards">{[["local","Local case","One primary country",MapPinIcon],["cross-border","Cross-border case","Two or more countries",Globe2],["international","International matter","Global or international rules",ScaleIcon]].map(([value,title,text,Icon])=><button key={String(value)} onClick={()=>setDraft({...draft,scope:String(value)})} className={draft.scope===value?"selected":""}><span className="selection-dot"/><Icon/><strong>{String(title)}</strong><p>{String(text)}</p></button>)}</div><InfoBox>Cross-border cases may need lawyers in more than one jurisdiction.</InfoBox></WizardSection>;
  if(step===2)return <WizardSection eyebrow="Jurisdiction" title="Which countries are connected to this case?" text="Select what you know. CaseBridge can flag other possible jurisdictions."><div className="form-grid"><label>Primary country<select value={draft.primary} onChange={e=>setDraft({...draft,primary:e.target.value})}>{jurisdictions.map(j=><option key={j.code}>{j.name}</option>)}</select></label><label>Region<select><option>Europe</option><option>Middle East</option><option>North America</option></select></label></div><label>Additional countries<div className="chip-select">{["Germany","United Kingdom","United States","France","European Union"].map(x=><button key={x} onClick={()=>setDraft({...draft,secondary:draft.secondary.includes(x)?draft.secondary.filter(y=>y!==x):[...draft.secondary,x]})} className={draft.secondary.includes(x)?"selected":""}>{draft.secondary.includes(x)&&<Check/>}{x}</button>)}</div></label><label className="checkbox unknown"><input type="checkbox"/> I am not sure which country&apos;s law applies</label><InfoBox>Not sure which country&apos;s law applies? CaseBridge can help identify possible jurisdictions. A lawyer must verify the final position.</InfoBox></WizardSection>;
  if(step===3)return <WizardSection eyebrow="Legal category" title="What is the main area of your case?" text="Choose the closest category. The analysis can identify related legal issues."><div className="category-grid">{legalCategories.map(x=><button key={x} onClick={()=>setDraft({...draft,category:x})} className={draft.category===x?"selected":""}><span>{categoryIcon(x)}</span>{x}{draft.category===x&&<Check/>}</button>)}</div></WizardSection>;
  if(step===4)return <WizardSection eyebrow="Case description" title="Tell us what happened" text="Use your own words. Include facts, not legal conclusions."><label>What happened?<textarea rows={6} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><button className="voice-button"><Mic/> Voice input <Badge>Demo</Badge></button></label><div className="form-grid"><label>When did it happen?<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Who is involved?<input value={draft.parties} onChange={e=>setDraft({...draft,parties:e.target.value})}/></label><label>What outcome do you want?<input value={draft.outcome} onChange={e=>setDraft({...draft,outcome:e.target.value})}/></label><label>Any known deadline?<input type="date" value={draft.deadline} onChange={e=>setDraft({...draft,deadline:e.target.value})}/></label></div><label>Has legal action already started?<select><option>No</option><option>Yes, a formal notice was sent</option><option>Yes, a claim was filed</option><option>Not sure</option></select></label></WizardSection>;
  if(step===5)return <WizardSection eyebrow="AI follow-up" title="A few questions will make your report more useful" text="These questions are based on your employment case. Skip anything you do not know."><div className="question-list">{["Was there a written employment contract?","Did you receive a written termination notice?","Were salary payments missing?","Do you have messages or emails from the employer?"].map((q,i)=><div className="question" key={q}><span>{i+1}</span><div><label>{q}</label><div className="yes-no"><button className={i!==1?"selected":""}>Yes</button><button className={i===1?"selected":""}>No</button><button>Not sure</button></div></div></div>)}</div><InfoBox>Additional evidence may change this preliminary assessment.</InfoBox></WizardSection>;
  if(step===6)return <WizardSection eyebrow="Evidence" title="Add documents and supporting material" text="Files are encrypted and will not be shown to lawyers without your permission."><button className="upload-zone" onClick={()=>setFiles([...files,`Salary-statement-${files.length+1}.pdf`])}><UploadCloud/><strong>Drop files here or browse</strong><span>PDF, DOCX, JPG, PNG, email exports and screenshots · up to 25 MB</span></button><div className="processing-list">{files.map((f,i)=><div className="processing-card" key={f}><FileText/><div><strong>{f}</strong><span>{i===0?"Employment contract":i===1?"Termination letter":"Payment record"} · PDF</span></div><Badge tone="green"><Check/> AI processed</Badge><span className="relevance">{96-i*4}% relevant</span><button aria-label={`Remove ${f}`} onClick={()=>setFiles(files.filter(x=>x!==f))}><Trash2/></button></div>)}</div><div className="encryption-note"><LockKeyhole/> Documents are encrypted in transit and at rest. Lawyers initially see summaries only.</div></WizardSection>;
  return <WizardSection eyebrow="Review & analyze" title="Check your case before analysis" text="You can return to any step to make changes."><div className="review-grid"><ReviewItem label="Case scope" value="Cross-border case" icon={<Globe2/>}/><ReviewItem label="Jurisdictions" value={`${draft.primary} + ${draft.secondary.join(", ")}`} icon={<MapPinIcon/>}/><ReviewItem label="Category" value={draft.category} icon={<BriefcaseBusiness/>}/><ReviewItem label="Important date" value="18 June 2026" icon={<CalendarDays/>}/></div><div className="review-block"><div><h3>Case description</h3><button>Edit</button></div><p>{draft.description}</p></div><div className="review-block"><div><h3>Evidence</h3><Badge tone="green">{files.length} files ready</Badge></div>{files.map(x=><p className="review-file" key={x}><FileCheck2/>{x}<Check/></p>)}</div><div className="missing-box"><AlertTriangle/><div><strong>Missing information</strong><p>A signed salary statement and any witness details could make the report more complete. You can analyze now and add them later.</p></div></div><Disclaimer/></WizardSection>;
}

function WizardSection({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children:React.ReactNode}){return <div className="wizard-section"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p className="wizard-intro">{text}</p>{children}</div>}
function InfoBox({children}:{children:React.ReactNode}){return <div className="info-box"><Info/>{children}</div>}
function ReviewItem({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="review-item"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function categoryIcon(x:string){return x==="Employment"?"EM":x==="Consumer rights"?"CR":x==="Contract"?"CO":x.slice(0,2).toUpperCase()}
const MapPinIcon=({size=24}:{size?:number})=><span className="pin-icon" style={{width:size,height:size}}/>;
const ScaleIcon=()=> <span className="scale-icon">§</span>;

export function AnalysisPage(){
  const [current,setCurrent]=useState(0); const [error,setError]=useState(false);
  useEffect(()=>{if(error||current>=analysisStages.length)return;const t=setTimeout(()=>setCurrent(c=>c+1),650);return()=>clearTimeout(t)},[current,error]);
  const done=current>=analysisStages.length;
  return <main className="analysis-page"><div className="analysis-brand"><a href="/"><span className="logo-mark"><span/></span>CaseBridge</a><span><LockKeyhole/> Private analysis</span></div><section className="analysis-card"><div className={`analysis-orb ${done?"done":""}`}>{done?<CheckCircle2/>:<Sparkles/>}<span/></div><span className="eyebrow">{done?"Analysis complete":"Preliminary analysis in progress"}</span><h1>{done?"Your case report is ready":"Organizing your case information"}</h1><p>{done?"Review the preliminary assessment, uncertainty notes and recommended next steps.":"This usually takes less than a minute in the demo. Please keep this page open."}</p><Progress value={done?100:Math.round(current/analysisStages.length*100)}/><div className="analysis-percent">{done?"100":Math.round(current/analysisStages.length*100)}%</div>
    <div className="analysis-stages">{analysisStages.map((s,i)=><div key={s.label} className={i<current?"complete":i===current?"active":""}><span>{i<current?<Check/>:i===current?<i/>:i+1}</span><div><strong>{s.label}</strong><small>{s.detail}</small></div>{i<current&&<em>Complete</em>}</div>)}</div>
    {error?<div className="analysis-error"><AlertTriangle/><span><b>Document processing paused</b>One file could not be read.</span><Button onClick={()=>setError(false)}>Retry</Button></div>:done?<Button href="/report" className="full">View preliminary report <ArrowRight/></Button>:<button className="link-button" onClick={()=>setError(true)}>Simulate processing issue</button>}
    <Disclaimer compact/></section></main>;
}

export function CaseReportPage(){
  return <AppShell active="Case reports"><div className="report-head"><div><a href="/dashboard"><ArrowLeft/> Cases</a><span className="eyebrow">Preliminary case report · RPT-1048</span><h1>Unpaid salary and termination dispute</h1><div className="case-meta"><Badge tone="green">Report ready</Badge><span><BriefcaseBusiness/> Employment</span><span><Globe2/> Turkey</span><span><CalendarDays/> 26 July 2026</span></div></div><div className="report-actions"><Button variant="secondary"><Download/> Download PDF</Button><Button href="/publish">Publish to lawyers <ArrowRight/></Button></div></div>
    <Disclaimer/>
    <div className="report-layout"><aside className="report-nav"><span>In this report</span>{["Overview","Case strength","Possible legal issues","Evidence analysis","Missing evidence","Deadlines","Next steps","Lawyer profile"].map((x,i)=><a key={x} href={`#report-${i}`} className={i===0?"active":""}>{x}</a>)}<div className="report-meta"><small>Generated</small><strong>26 Jul 2026, 10:14</strong><small>Based on</small><strong>4 documents, 10 answers</strong></div></aside>
      <article className="report-content"><ReportSection id="report-0" number="01" title="Case overview"><div className="summary-callout"><Sparkles/><div><strong>Plain-language summary</strong><p>Based on the information provided, your employer appears to have ended the employment relationship after salary payments were delayed. The documents may support questions about unpaid wages, notice requirements and the termination process under Turkish law. A lawyer should verify the applicable rules and review the original documents.</p></div></div><div className="fact-grid"><Fact label="Primary jurisdiction" value="Turkey" note="Lawyer verification required"/><Fact label="Additional jurisdiction" value="None identified" note="May change with new information"/><Fact label="Known deadline" value="15 August 2026" note="User-provided; not verified"/><Fact label="Documents reviewed" value="4" note="All processed"/></div></ReportSection>
      <ReportSection id="report-1" number="02" title="Preliminary case strength"><div className="strength-card"><div className="strength-gauge"><span>Moderate</span><i/></div><div><Badge tone="amber">Moderate supporting evidence</Badge><h3>There is useful written evidence, with important gaps.</h3><p>The contract, messages and termination email support parts of the timeline. The absence of a signed salary record and formal notice limits what can be assessed.</p><div className="confidence-note"><Info/>This qualitative label is not a prediction of success. Additional evidence, legal defenses and the applicable law may change the assessment.</div></div></div></ReportSection>
      <ReportSection id="report-2" number="03" title="Possible legal issues"><div className="issue-grid">{[["Unpaid salary claim","Salary statements and messages may indicate delayed or missing payments.","Salary statements, WhatsApp messages","Signed payment ledger"],["Notice period dispute","The termination email may raise questions about notice requirements.","Termination email, contract","Formal notice record"],["Contract violation","The written contract may help clarify payment and termination obligations.","Employment contract","Employer policies"],["Termination process","The available record may warrant review of the procedure used.","Email correspondence","Witness information"]].map((x,i)=><div className="issue-card" key={x[0]}><div><span>{i+1}</span><Badge tone={i<2?"blue":"neutral"}>{i<2?"Review priority":"Potential issue"}</Badge></div><h3>{x[0]}</h3><p>{x[1]}</p><dl><dt>Supporting evidence</dt><dd><Check/> {x[2]}</dd><dt>Still missing</dt><dd><AlertTriangle/> {x[3]}</dd><dt>Jurisdiction</dt><dd><Globe2/> Turkey · verify with lawyer</dd></dl></div>)}</div></ReportSection>
      <ReportSection id="report-3" number="04" title="Evidence analysis"><div className="evidence-table"><div className="table-head"><span>Document</span><span>Classification</span><span>Relevant issue</span><span>Strength</span><span>Date</span></div>{[["Employment contract.pdf","Employment contract","Contract / notice","Strong","02 Jan 2024"],["Salary-statements.pdf","Payment record","Unpaid salary","Strong","Jan–May 2026"],["WhatsApp-export.pdf","Correspondence","Salary / timeline","Moderate","Mar–Jun 2026"],["Termination-email.pdf","Termination letter","Notice / process","Moderate","18 Jun 2026"]].map(r=><div className="table-row" key={r[0]}><span><FileText/><b>{r[0]}</b></span><span>{r[1]}</span><span>{r[2]}</span><span><Badge tone={r[3]==="Strong"?"green":"amber"}>{r[3]}</Badge></span><span>{r[4]}</span></div>)}</div></ReportSection>
      <ReportSection id="report-4" number="05" title="Missing evidence"><div className="missing-list">{[["Critical","Signed salary/payment record","Could help confirm which payments remain outstanding."],["Recommended","Formal termination notice","May clarify notice dates and stated reason."],["Recommended","Witness contact details","Could support the employment timeline."],["Optional","Internal employee policies","May provide useful context on procedure."]].map(x=><div key={x[1]}><Badge tone={x[0]==="Critical"?"red":x[0]==="Recommended"?"amber":"neutral"}>{x[0]}</Badge><div><strong>{x[1]}</strong><p>{x[2]}</p></div><Button variant="ghost"><Plus/> Add</Button></div>)}</div></ReportSection>
      <ReportSection id="report-5" number="06" title="Important deadlines"><div className="deadline-warning"><AlertTriangle/><div><Badge tone="red">Approaching date</Badge><h3>15 August 2026 · user-provided deadline</h3><p>This date has not been legally verified. Limitation periods and procedural deadlines depend on the applicable law and facts. Contact a licensed lawyer promptly.</p></div><Button href="/lawyer/marketplace" variant="secondary">Find a lawyer</Button></div></ReportSection>
      <ReportSection id="report-6" number="07" title="Possible next steps"><div className="next-step-list">{["Collect the missing salary and termination records","Preserve original messages and document metadata","Ask a specialist lawyer to verify deadlines and jurisdiction","Consider a formal notice only after legal review","Avoid signing a settlement before obtaining legal advice"].map((x,i)=><div key={x}><span>{i+1}</span><strong>{x}</strong>{i<3&&<Badge tone={i===2?"red":"blue"}>{i===2?"Time-sensitive":"Recommended"}</Badge>}</div>)}</div></ReportSection>
      <ReportSection id="report-7" number="08" title="Recommended lawyer profile"><div className="recommended-profile"><div className="lawyer-portrait">AD<BadgeCheckSmall/></div><div><Badge tone="teal">6 matching lawyers</Badge><h3>Employment lawyer licensed in Turkey</h3><div className="profile-tags"><span><BriefcaseBusiness/> Employment & termination</span><span><Languages/> Turkish and English</span><span><Globe2/> Cross-border awareness</span><span><Clock3/> 7+ years recommended</span></div></div><Button href="/lawyer/marketplace">View lawyer matches <ArrowRight/></Button></div></ReportSection>
      <div className="report-final-actions"><Button variant="secondary"><FilePlus2/> Add evidence</Button><Button variant="secondary"><MessageSquare/> Ask follow-up</Button><Button href="/publish">Publish case to lawyers <ArrowRight/></Button></div><Disclaimer/></article></div>
  </AppShell>;
}

function ReportSection({id,number,title,children}:{id:string;number:string;title:string;children:React.ReactNode}){return <section className="report-section" id={id}><div className="report-section-title"><span>{number}</span><h2>{title}</h2></div>{children}</section>}
function Fact({label,value,note}:{label:string;value:string;note:string}){return <div className="fact"><small>{label}</small><strong>{value}</strong><span>{note}</span></div>}
function BadgeCheckSmall(){return <span className="verified-dot"><Check/></span>}

export function PublishPage(){
  const [published,setPublished]=useState(false); const [confirm,setConfirm]=useState(false);
  if(published)return <AppShell active="Case reports"><div className="success-screen"><div className="success-icon"><Check/></div><Badge tone="green">Published securely</Badge><h1>Your anonymous case is now visible to matched lawyers.</h1><p>Your identity, company names and original documents remain hidden. You control every access request.</p><div className="success-stats"><span><strong>6</strong> matched lawyers</span><span><strong>3</strong> jurisdictions covered</span><span><strong>100%</strong> identity hidden</span></div><div><Button href="/dashboard">Return to dashboard</Button><Button href="/lawyer/marketplace" variant="secondary">Preview marketplace</Button></div></div></AppShell>;
  return <AppShell active="Case reports"><PageTitle eyebrow="Publish anonymously" title="Choose what lawyers can see" text="Your privacy settings apply before the case enters the marketplace."/>
    <div className="publish-layout"><section className="panel publish-form"><h2>Case listing</h2><div className="form-grid"><label>Anonymous case title<input defaultValue="Employment pay and termination dispute"/></label><label>Legal category<select><option>Employment</option></select></label></div><label>Short case summary<textarea rows={5} defaultValue="Employee seeking advice after delayed salary payments and termination. Written contract, payment records and correspondence are available."/></label><div className="form-grid"><label>Jurisdiction<select><option>Turkey</option></select></label><label>Preferred lawyer language<select><option>Turkish or English</option></select></label><label>Budget range<select><option>$500–$1,500</option></select></label><label>Urgency<select><option>High · possible deadline</option></select></label></div><div className="toggle-list"><Toggle title="Remote consultation accepted" text="Lawyers may offer video or phone consultations" checked/><Toggle title="In-person consultation accepted" text="Only show lawyers able to meet locally"/><Toggle title="Allow cross-border legal team" text="Lawyers may collaborate across jurisdictions" checked/></div><h2>Privacy controls</h2><div className="privacy-control-list"><Toggle title="Hide personal identity" text="Your name and contact information stay private" checked locked/><Toggle title="Hide company names" text="Replace employer and organization names with neutral labels" checked/><Toggle title="Hide sensitive documents" text="Lawyers see AI summaries until you grant access" checked/></div><label className="checkbox consent"><input type="checkbox" defaultChecked/> I consent to publishing this anonymized summary to verified lawyers.</label><Button onClick={()=>setConfirm(true)} className="full">Publish case anonymously <ArrowRight/></Button></section>
      <aside className="panel preview-panel"><div className="panel-head"><h2>What lawyers will see</h2><Badge tone="green"><Eye/> Live preview</Badge></div><div className="market-case-preview"><div className="preview-badges"><Badge tone="blue">Employment</Badge><Badge tone="red">High urgency</Badge></div><h3>Employment pay and termination dispute</h3><p>Employee seeking advice after delayed salary payments and termination. Written contract, payment records and correspondence are available.</p><div className="preview-facts"><span><Globe2/>Turkey</span><span><Languages/>Turkish or English</span><span><FileCheck2/>4 document summaries</span><span><BriefcaseBusiness/>$500–$1,500</span></div><div className="identity-hidden"><LockKeyhole/><div><strong>Identity protected</strong><p>Name, contact details, company names and original files are hidden.</p></div></div></div><div className="access-summary"><h3>Access rules</h3><p><Check/> Verified lawyers only</p><p><Check/> You approve every document request</p><p><Check/> Full access history recorded</p></div></aside></div>
      {confirm&&<div className="modal-backdrop"><div className="confirmation-modal" role="dialog" aria-modal="true" aria-labelledby="publish-title"><button className="modal-close" onClick={()=>setConfirm(false)}><X/></button><div className="modal-icon"><ShieldCheck/></div><h2 id="publish-title">Ready to publish anonymously?</h2><p>Six verified lawyers may see this summary. Your identity and original documents remain protected.</p><div className="confirmation-points"><span><Check/> Identity hidden</span><span><Check/> Company names hidden</span><span><Check/> Documents require approval</span></div><div className="modal-actions"><Button variant="secondary" onClick={()=>setConfirm(false)}>Review settings</Button><Button onClick={()=>setPublished(true)}>Confirm publication</Button></div></div></div>}
  </AppShell>;
}
function Toggle({title,text,checked,locked}:{title:string;text:string;checked?:boolean;locked?:boolean}){return <label className="toggle-row"><div><strong>{title}</strong><span>{text}</span></div><span className={`toggle ${checked?"on":""} ${locked?"locked":""}`}><input type="checkbox" defaultChecked={checked} disabled={locked}/><i/></span></label>}

export function MessagesPage(){
  const [sent,setSent]=useState(false);
  return <AppShell active="Messages"><PageTitle eyebrow="Secure communication" title="Messages" text="Share case context while keeping personal data permission-based."/>
    <div className="messages-layout"><aside className="conversations"><div className="conversation-search"><Search/><input placeholder="Search conversations"/></div>{lawyers.slice(0,4).map((l,i)=><button className={`conversation ${i===0?"active":""}`} key={l.id}><span className="avatar">{l.initials}</span><div><strong>{l.name}{l.verified&&<UserCheck/>}</strong><p>{i===0?"I reviewed the case summary and...":"Your case may require..."}</p></div><small>{i===0?"09:42":"Yesterday"}</small>{i<2&&<i/>}</button>)}</aside><section className="chat-panel"><header><div><span className="avatar">AD</span><div><strong>Aylin Demir <Badge tone="green"><UserCheck/>Verified</Badge></strong><small>Employment lawyer · Turkey</small></div></div><button><MoreHorizontal/></button></header><div className="permission-banner"><LockKeyhole/><span><b>Document access is off.</b> Aylin can see the case report summary, not your identity or original files.</span><button>Manage access</button></div><div className="messages"><span className="date-divider">Today</span><div className="message incoming"><p>Hello. I reviewed your anonymized report. Based on the information provided, the payment and notice questions may be worth a closer legal review.</p><small>09:31</small></div><div className="message outgoing"><p>Thank you. Would you be able to verify whether the deadline I entered may apply?</p><small>09:37 · Read</small></div><div className="message incoming"><p>I can review that, but I would need the exact employment dates and the original termination notice. You can grant document access without revealing everything else.</p><small>09:42</small></div>{sent&&<div className="message outgoing"><p>That makes sense. I will review the access settings and share the relevant files.</p><small>Now</small></div>}</div><div className="chat-compose"><button><Paperclip/></button><input placeholder="Write a secure message..." onKeyDown={e=>{if(e.key==="Enter")setSent(true)}}/><button className="send-button" onClick={()=>setSent(true)}><Send/></button></div></section><aside className="case-context"><span className="eyebrow">Case context</span><h3>Unpaid salary and termination</h3><Badge tone="green">Report ready</Badge><dl><dt>Jurisdiction</dt><dd>Turkey</dd><dt>Category</dt><dd>Employment</dd><dt>Shared with lawyer</dt><dd>Report summary</dd></dl><div className="context-permission"><ShieldCheck/><strong>Your permissions</strong><p>Identity hidden</p><p>Original documents locked</p></div><Button href="/report" variant="secondary" className="full">View case report</Button></aside></div>
  </AppShell>;
}

export function SettingsPage(){
  const sections=["Profile","Language & country","Notifications","Privacy","Document permissions","Account security","Data export","Lawyer access history"];
  return <AppShell active="Settings"><PageTitle eyebrow="Account preferences" title="Settings" text="Manage your profile, privacy and security."/><div className="settings-layout"><nav>{sections.map((s,i)=><button className={i===3?"active":""} key={s}>{s}<ArrowRight/></button>)}</nav><section className="panel settings-panel"><h2>Privacy</h2><p>Control how your identity, cases and documents are handled.</p><div className="settings-group"><h3>Default case visibility</h3><Toggle title="Publish cases anonymously" text="Hide your identity by default on new marketplace listings" checked/><Toggle title="Hide organization names" text="Automatically redact employer and company names" checked/><Toggle title="Require approval for every document" text="Lawyers can only see document summaries until approved" checked locked/></div><div className="settings-group"><h3>Data & analysis</h3><Toggle title="Use documents for case analysis" text="Allow AI processing within your private workspace" checked/><Toggle title="Improve CaseBridge with anonymized usage data" text="Never includes original document content"/></div><div className="settings-group"><h3>Recent lawyer access</h3><div className="access-row"><span className="avatar">AD</span><div><strong>Aylin Demir</strong><small>Report summary only · 26 Jul 2026</small></div><Badge tone="green">Active</Badge><Button variant="ghost">Review</Button></div><div className="access-row"><span className="avatar">JW</span><div><strong>Jonas Weber</strong><small>Listing only · 25 Jul 2026</small></div><Badge>Expired</Badge><Button variant="ghost">Review</Button></div></div><Button>Save privacy settings</Button></section></div>
  </AppShell>;
}
